/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.curso.view;

import br.com.ifba.curso.dao.CursoDao;
import br.com.ifba.curso.dao.CursoIDao;
import br.com.ifba.curso.entity.Curso;
import jakarta.persistence.EntityManager;
import jakarta.persistence.EntityManagerFactory;
import jakarta.persistence.Persistence;
import java.util.logging.Level;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author igo
 */
public class CursoAtualizar extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CursoAtualizar.class.getName());

    /**
     * Creates new form CursoAtualizar
     */
    
    private Curso cursoSelecionado;
    
    public CursoAtualizar() {
        initComponents();
        
    }
    
     private CursoListar telaPrincipal; // **SUBSTITUA** pelo nome real da sua classe principal
   
     
     /**
     * Construtor recomendado.
     * Recebe a tela principal, obtém o curso selecionado nela e preenche
     * os campos com os dados antigos.
     *
     * @param telaPrincipal referência da janela que lista os cursos
     */
    public CursoAtualizar(CursoListar telaPrincipal) {
        initComponents();
        this.telaPrincipal = telaPrincipal; // Armazena a referência
        this.cursoSelecionado = telaPrincipal.getCursoSelecionado();
         // Caso um curso esteja selecionado, preenche as labels com dados antigos
         if(cursoSelecionado != null){
             lblCodigoCurosoAntigo.setText(cursoSelecionado.getCodigo());
             lblNomeCursoAntigo.setText(cursoSelecionado.getNome());
             
        }else{

        }
    }
    
    /**
     * Salva as alterações realizadas pelo usuário no banco de dados.
     * Realiza validações, abre transação JPA, atualiza o objeto Curso,
     * dá merge e confirma a transação.
     *
     * Exibe mensagens de sucesso ou erro conforme o resultado.
     */
    private void salvarEdicao() {
        String novoCodigo = txtNovoCodigo.getText();
        String novoNome = txtNovoNome.getText();
         if (novoCodigo.isEmpty() || novoNome.isEmpty()) {
             JOptionPane.showMessageDialog(this, "Preencha todos os campos.");
             return;
         }
            
         cursoSelecionado.setCodigo(novoCodigo);
         cursoSelecionado.setNome(novoNome);
         
         CursoIDao cursoAtualizar = new CursoDao();
         
         Curso verificar = new Curso();
         
         verificar = cursoAtualizar.findById(cursoSelecionado.getId());
         if(verificar != null){
            cursoAtualizar.save(cursoSelecionado);
            JOptionPane.showMessageDialog(this, "Curso atualizado!");
            dispose();
         }else{
             JOptionPane.showMessageDialog(this, "Não foi possível atualizar");
             dispose();
         }
       
     }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTextoAtualizarCurso = new javax.swing.JLabel();
        lblNomeCursoAntigo = new javax.swing.JLabel();
        lblCodigoCurosoAntigo = new javax.swing.JLabel();
        lblTextoNovoNome = new javax.swing.JLabel();
        lblTextoNovoCodigo = new javax.swing.JLabel();
        txtNovoNome = new javax.swing.JTextField();
        txtNovoCodigo = new javax.swing.JTextField();
        btnAtualizar = new javax.swing.JButton();
        pnAtualizar = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTextoAtualizarCurso.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTextoAtualizarCurso.setText("Atualizar Curso");
        getContentPane().add(lblTextoAtualizarCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, -1, -1));

        lblNomeCursoAntigo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNomeCursoAntigo.setText("jLabel1");
        getContentPane().add(lblNomeCursoAntigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, -1, -1));

        lblCodigoCurosoAntigo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCodigoCurosoAntigo.setText("jLabel2");
        getContentPane().add(lblCodigoCurosoAntigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, -1, -1));

        lblTextoNovoNome.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTextoNovoNome.setText("Novo Nome");
        getContentPane().add(lblTextoNovoNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, -1, -1));

        lblTextoNovoCodigo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTextoNovoCodigo.setText("Novo Codigo");
        getContentPane().add(lblTextoNovoCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, -1, -1));

        txtNovoNome.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(txtNovoNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 210, -1));

        txtNovoCodigo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(txtNovoCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 210, -1));

        btnAtualizar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnAtualizar.setText("Atualizar");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAtualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 273, 120, 40));

        javax.swing.GroupLayout pnAtualizarLayout = new javax.swing.GroupLayout(pnAtualizar);
        pnAtualizar.setLayout(pnAtualizarLayout);
        pnAtualizarLayout.setHorizontalGroup(
            pnAtualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );
        pnAtualizarLayout.setVerticalGroup(
            pnAtualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );

        getContentPane().add(pnAtualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
           salvarEdicao();
           this.telaPrincipal.carregarCursos(); 
           this.dispose();
    }//GEN-LAST:event_btnAtualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CursoAtualizar().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JLabel lblCodigoCurosoAntigo;
    private javax.swing.JLabel lblNomeCursoAntigo;
    private javax.swing.JLabel lblTextoAtualizarCurso;
    private javax.swing.JLabel lblTextoNovoCodigo;
    private javax.swing.JLabel lblTextoNovoNome;
    private javax.swing.JPanel pnAtualizar;
    private javax.swing.JTextField txtNovoCodigo;
    private javax.swing.JTextField txtNovoNome;
    // End of variables declaration//GEN-END:variables
}
