/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.curso.view;

import br.com.ifba.CursoSave;
import br.com.ifba.curso.entity.Curso;
import javax.swing.JOptionPane;

/**
 *
 * @author igo
 */
public class NovoCurso extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(NovoCurso.class.getName());

    /**
     * Creates new form NovoCurso
     */
    public NovoCurso() {
        initComponents();
    }
    
     /**
     * Construtor recomendado.
     * Recebe a tela principal para que, após criar um novo curso,
     * seja possível atualizar a tabela imediatamente.
     *
     * @param telaPrincipal instancia de {@link CursoListar} que chamou esta tela
     */
    
    private CursoListar telaPrincipal; 
   
    public NovoCurso(CursoListar telaPrincipal) {
        initComponents();
        this.telaPrincipal = telaPrincipal; // Armazena a referência
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTextoAdicionar = new javax.swing.JLabel();
        lblTextoNome = new javax.swing.JLabel();
        lblTextoCodigo = new javax.swing.JLabel();
        txtNomeCurso = new javax.swing.JTextField();
        txtCodigo = new javax.swing.JTextField();
        btnAdicionar = new javax.swing.JButton();
        pnAdicionar = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTextoAdicionar.setFont(new java.awt.Font("Liberation Sans", 0, 36)); // NOI18N
        lblTextoAdicionar.setText("Adicionar Novo Curso");
        getContentPane().add(lblTextoAdicionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 22, -1, -1));

        lblTextoNome.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        lblTextoNome.setText("Nome");
        getContentPane().add(lblTextoNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 116, -1, -1));

        lblTextoCodigo.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        lblTextoCodigo.setText("Codigo");
        getContentPane().add(lblTextoCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 181, -1, -1));

        txtNomeCurso.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        getContentPane().add(txtNomeCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 111, 309, -1));

        txtCodigo.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        getContentPane().add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 176, 313, -1));

        btnAdicionar.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        btnAdicionar.setText("Adicionar");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdicionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 291, 252, 47));

        javax.swing.GroupLayout pnAdicionarLayout = new javax.swing.GroupLayout(pnAdicionar);
        pnAdicionar.setLayout(pnAdicionarLayout);
        pnAdicionarLayout.setHorizontalGroup(
            pnAdicionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        pnAdicionarLayout.setVerticalGroup(
            pnAdicionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );

        getContentPane().add(pnAdicionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        // TODO add your handling code here:
        Curso novoCurso = new Curso(txtNomeCurso.getText(), txtCodigo.getText());
         // Classe responsável por salvar o curso no banco (persistência JPA)
        CursoSave salvar = new CursoSave();
        salvar.save(novoCurso);
        JOptionPane.showMessageDialog(null, "Curso " + txtNomeCurso.getText() + " Salvo com sucesso");
         
        if (this.telaPrincipal != null) {
            this.telaPrincipal.adicionarLinhaNaTabela(novoCurso); 
        }
        
        this.dispose();
        
    }//GEN-LAST:event_btnAdicionarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new NovoCurso().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JLabel lblTextoAdicionar;
    private javax.swing.JLabel lblTextoCodigo;
    private javax.swing.JLabel lblTextoNome;
    private javax.swing.JPanel pnAdicionar;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtNomeCurso;
    // End of variables declaration//GEN-END:variables
}
